create sequence entrance_sequence start with 1 increment by 1;

create table entrances (
   "ID" integer generated by default as sequence entrance_sequence primary key
  ,"CODE" varchar(50) not null
  ,"NUMBER" integer not null
  ,"FILENAMES" varchar(100) default null
  ,"ERROR" varchar(100) default null
  ,unique("NUMBER", "CODE", "ID")
);