create sequence entrance_sequence start with 1 increment by 1;

create table entrances (
   "id" integer generated by default as sequence entrance_sequence primary key
  ,"code" varchar(50) default '00.Result.OK'
  ,"number" integer not null
  ,"filenames" varchar(100) default null
  ,"error" varchar(100) default null
  ,unique("number", "code")
);